# vim: noexpandtab:ts=4:sw=4

provider = coldrye
os = debian
release = testing
feature = ruby
feature_version = 2.3.x
tag := $(shell date +"%Y%m%d%H%M%S")
image = $(os)-$(feature)

include ../../Makefile.in

